import type { SkillEdge, SkillNode } from './skills-graph.types'

export const DEFAULT_SKILL_NODES: SkillNode[] = [
  { id: 'vue', label: 'Vue', category: 'frontend', level: 5, x: -221.7, y: -76.9 },
  { id: 'nuxt', label: 'Nuxt', category: 'frontend', level: 5, x: -244.7, y: -0.9 },
  { id: 'typescript', label: 'TypeScript', category: 'fullstack', level: 5, x: -118.3, y: -105.3 },
  { id: 'javascript', label: 'JavaScript', category: 'fullstack', level: 5, x: -123.2, y: -32.9 },
  { id: 'react', label: 'React', category: 'frontend', level: 4, x: -256.4, y: -123.4 },
  { id: 'tailwind', label: 'Tailwind', category: 'frontend', level: 4, x: -309.4, y: -4.8 },
  { id: 'vite', label: 'Vite', category: 'frontend', level: 4, x: -252.8, y: 112.4 },
  { id: 'node', label: 'Node.js', category: 'backend', level: 5, x: -12.6, y: -57.5 },
  { id: 'nestjs', label: 'NestJS', category: 'backend', level: 4, x: 114.1, y: -104.3 },
  { id: 'express', label: 'Express', category: 'backend', level: 4, x: 84.4, y: -48.8 },
  { id: 'python', label: 'Python', category: 'backend', level: 4, x: 213, y: -135.8 },
  { id: 'go', label: 'Go', category: 'backend', level: 3, x: 380, y: -5.8 },
  { id: 'java', label: 'Java', category: 'backend', level: 3, x: 401.9, y: 41.4 },
  { id: 'postgres', label: 'PostgreSQL', category: 'data', level: 5, x: 120.3, y: 146.8 },
  { id: 'mysql', label: 'MySQL', category: 'data', level: 4, x: 188.8, y: 249 },
  { id: 'redis', label: 'Redis', category: 'data', level: 4, x: 139.9, y: 22.9 },
  { id: 'elasticsearch', label: 'Elasticsearch', category: 'data', level: 3, x: 251.3, y: 201.1 },
  { id: 'docker', label: 'Docker', category: 'devops', level: 5, x: -35.9, y: 151.8 },
  { id: 'kubernetes', label: 'Kubernetes', category: 'devops', level: 4, x: -81.3, y: 242.2 },
  { id: 'aws', label: 'AWS', category: 'devops', level: 4, x: -26.5, y: 290.8 },
  { id: 'gcp', label: 'GCP', category: 'devops', level: 3, x: 101.3, y: 371.2 },
  { id: 'terraform', label: 'Terraform', category: 'devops', level: 3, x: -143, y: 335.1 },
  { id: 'ansible', label: 'Ansible', category: 'devops', level: 2, x: -266.3, y: 308.7 },
  { id: 'rabbitmq', label: 'RabbitMQ', category: 'backend', level: 3, x: 277.7, y: -121.9 },
  { id: 'kafka', label: 'Kafka', category: 'backend', level: 3, x: 403.3, y: -79.6 },
  { id: 'graphql', label: 'GraphQL', category: 'fullstack', level: 4, x: -45.9, y: 27.7 },
  { id: 'rest', label: 'REST API', category: 'fullstack', level: 5, x: 41.7, y: 34.9 },
  { id: 'grpc', label: 'gRPC', category: 'backend', level: 3, x: 461.3, y: 30.5 },
  { id: 'vitest', label: 'Vitest', category: 'frontend', level: 4, x: -349.5, y: 164.1 },
  { id: 'playwright', label: 'Playwright', category: 'frontend', level: 3, x: -459.3, y: 145.3 },
  { id: 'llm', label: 'LLM Ops', category: 'ai', level: 4, x: 22, y: -225.5 },
  { id: 'rag', label: 'RAG', category: 'ai', level: 4, x: 115.9, y: -185.6 },
  { id: 'agents', label: 'AI Agents', category: 'ai', level: 5, x: -52.4, y: -200.2 },
  { id: 'prompting', label: 'Prompting', category: 'ai', level: 5, x: -135.3, y: -260.3 },
  { id: 'langchain', label: 'LangChain', category: 'ai', level: 3, x: 42.9, y: -275.3 },
  { id: 'pytorch', label: 'PyTorch', category: 'ai', level: 2, x: 283.4, y: -219.2 },
]

export const DEFAULT_SKILL_EDGES: SkillEdge[] = [
  { source: 'vue', target: 'nuxt', weight: 1.8 },
  { source: 'vue', target: 'typescript', weight: 1.5 },
  { source: 'vue', target: 'tailwind', weight: 1.2 },
  { source: 'react', target: 'typescript', weight: 1.1 },
  { source: 'nuxt', target: 'vite', weight: 1.2 },
  { source: 'javascript', target: 'typescript', weight: 1.6 },
  { source: 'typescript', target: 'node', weight: 1.4 },
  { source: 'node', target: 'nestjs', weight: 1.4 },
  { source: 'node', target: 'express', weight: 1.3 },
  { source: 'node', target: 'rest', weight: 1.5 },
  { source: 'node', target: 'graphql', weight: 1.2 },
  { source: 'python', target: 'pytorch', weight: 1.2 },
  { source: 'python', target: 'rag', weight: 1.2 },
  { source: 'go', target: 'grpc', weight: 1.4 },
  { source: 'java', target: 'kafka', weight: 1.2 },
  { source: 'postgres', target: 'mysql', weight: 1 },
  { source: 'postgres', target: 'redis', weight: 1.3 },
  { source: 'postgres', target: 'elasticsearch', weight: 0.9 },
  { source: 'docker', target: 'kubernetes', weight: 1.7 },
  { source: 'docker', target: 'aws', weight: 1.3 },
  { source: 'kubernetes', target: 'terraform', weight: 1.1 },
  { source: 'terraform', target: 'aws', weight: 1 },
  { source: 'aws', target: 'gcp', weight: 0.8 },
  { source: 'ansible', target: 'terraform', weight: 0.9 },
  { source: 'rabbitmq', target: 'kafka', weight: 1 },
  { source: 'rabbitmq', target: 'nestjs', weight: 1.1 },
  { source: 'graphql', target: 'rest', weight: 1.1 },
  { source: 'vitest', target: 'playwright', weight: 1 },
  { source: 'vite', target: 'vitest', weight: 1.1 },
  { source: 'llm', target: 'rag', weight: 1.5 },
  { source: 'llm', target: 'agents', weight: 1.7 },
  { source: 'prompting', target: 'agents', weight: 1.5 },
  { source: 'langchain', target: 'agents', weight: 1.3 },
  { source: 'langchain', target: 'rag', weight: 1.1 },
  { source: 'typescript', target: 'agents', weight: 1 },
  { source: 'node', target: 'agents', weight: 1.1 },
  { source: 'redis', target: 'rag', weight: 0.9 },
  { source: 'docker', target: 'node', weight: 1 },
  { source: 'postgres', target: 'rest', weight: 1 },
  { source: 'tailwind', target: 'vite', weight: 0.8 },
]
